version: 2
sources:
  - name: raw
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF10
    tables:
      - name: ORDERS
        freshness:
        warn_after: { count: 24, period: hour }
        error_after:: { count: 48, period: hour }
      - name: CUSTOMER
        freshness:
        warn_after: { count: 24, period: hour }
        error_after:: { count: 48, period: hour }
      - name: LINEITEM
        freshness:
        warn_after: { count: 24, period: hour }
        error_after:: { count: 48, period: hour }
